GET http://localhost:80/api/tasks/category/list

###
GET http://localhost:80/api/tasks/category/?productId=2

###
GET http://localhost:80/api/tasks/product/list

###
GET http://localhost:80/api/tasks/product/details/?productId=1


###
GET http://localhost:80/api/tasks/order/details/?orderId=1

###
GET http://localhost:80/api/tasks/payment/details/?paymentId=2



